### ISSUE TITLE
Fitur apa saja yang akan dikembangkan di package ini?

### ISSUE THREAD

**Issue by azulkipli** [harrypujianto/Veritrans-Laravel5#1]
Maaf gan kenapa kita butuh package ini ? 
Ada repo ini kan https://github.com/veritrans/veritrans-php kita tinggal composer require dan Use aja
Mudah-mudahan ada rencana tambahan fitur lain selain sekedar wrapper untuk Laravel.

**Comment by harrypujianto** [comment]
sadly, masih ada orang yang ga ngerti bahwa package bisa di ambil dari composer. 
Masih ada yang request untuk wrapper laravel. so package ini hanya memudahkan mereka yang membutuhkan. 

feel free to choose..
