### ISSUE TITLE
Midtrans Status Error

### ISSUE THREAD

**Issue by JFOC** [harrypujianto/Veritrans-Laravel5#10]
Halo,
Saya coba untuk midtrans->status dan berhasil mendapatkan return resultnya.
Tetapi pada Midtrans.php line 135 memberikan error, hanya karena http_codenya return 200

`if ($info['http_code'] != 201) {
        $message = 'Midtrans Error (' . $info['http_code'] . '): '
            . implode(',', $result_array->error_messages);
        throw new Exception($message, $info['http_code']);`

Apakah ini bugs atau kesalahan logic ?
Sebelum $result_array->error_messages apakah tidak lebih baik diberikan pengecekan dulu, untuk menghindari exception 'ErrorException' with message 'Undefined property: stdClass::$error_messages'

**Comment by harrypujianto** [comment]
Unutk get status silahkan lihat ke transaction controller. dan yang digunakan adalah Veritrans bukan midtrans. Karena midtrans hanya akan difokuskan untuk snap get token saja..

**Comment by JFOC** [comment]
Untuk saat ini yang digunakan dalam keperluan Snap, menyesuaikan dengan SnapController. Midtrans bukan Veritrans. Apakah harus ganti ke Veritrans ? Dan sudah di live production.

**Comment by harrypujianto** [comment]
tidak. Untuk get token snap menggunakan library yang midtrans. Untuk CORE API, get status, cancel, expire menggunakan library veritrans.
