### ISSUE TITLE
CURL Error: Could not resolve host: app.sandbox.midtrans.com; Name or service not known

### ISSUE THREAD

**Issue by nanangkoesharwanto** [harrypujianto/Veritrans-Laravel5#14]
ketika digunakan dalam iframe, selalu keluar tampiran error.

"Kami tidak menemukan transaksi Anda
Transaksi Anda tidak tersedia, atau URL yang Anda masukkan salah."

dan saat saya cek di firebug, keterangan error nya adalah :

"CURL Error: Could not resolve host: app.sandbox.midtrans.com; Name or service not known"

kemudian, setelah saya refresh via javascript (location.reload()), dan saya coba lagi, hasil nya sukses keluar form pembayarannya.
Apakah ada yg harus disesuaikan ketika digunakan di dalam iframe?

terima kasih banyak.

**Comment by harrypujianto** [comment]
untuk curl error biasanya masalah koneksi. Jika beberapa saat kemudian bisa tampil dan tidak ada masalah, berarti hanya koneksi yang intermitten. namun jika berkelanjutan ada masalah di dns server. tidak ada yang harus disesuaikan terlebih jika sudah berhasil menampilkan form iframe.

**Comment by husenEF** [comment]
saya juga nemu masalah seperti ini mas @harrypujianto 
tapi ini dari server BE
`CURL Error: Could not resolve host: app.sandbox.midtrans.com`
klo dari local, script ini jalan, tapi ketika di server..return error seperti di atas

**Comment by faruq-id** [comment]
> saya juga nemu masalah seperti ini mas @harrypujianto
> tapi ini dari server BE
> `CURL Error: Could not resolve host: app.sandbox.midtrans.com`
> klo dari local, script ini jalan, tapi ketika di server..return error seperti di atas

bagaimana cara menghandle keterangan error seperti ini, maksudnya ketika terjadi error seperti itu pesan errornya di ganti pesan lain sesuai keinginan kita

**Comment by husenEF** [comment]
> > saya juga nemu masalah seperti ini mas @harrypujianto
> > tapi ini dari server BE
> > `CURL Error: Could not resolve host: app.sandbox.midtrans.com`
> > klo dari local, script ini jalan, tapi ketika di server..return error seperti di atas
> 
> bagaimana cara menghandle keterangan error seperti ini, maksudnya ketika terjadi error seperti itu pesan errornya di ganti pesan lain sesuai keinginan kita

siap mas, terimakasih sarannya :)

**Comment by Rvldo** [comment]
tidak ada solusi ?

**Comment by RobyCigar** [comment]
solved, barusan nemu ginian tp ternyata krn gaada koneksi gan wkwk
