### ISSUE TITLE
Get info from midtrans and save to database

### ISSUE THREAD

**Issue by robertnicjoo** [harrypujianto/Veritrans-Laravel5#17]
Hi,
I have working snap where I can purchase successfully but on redirect i go to another page and receive error while my transaction was successful.

**Here is how my url's are:**

`domain/orders` (I pay here with snap)
`domain/orderspayonline/7` (here is where i redirect and receive error)

**ERROR:**

```php
Class 'App\Veritrans\Exception' not found
```
on

```php
      else {
        $result_array = json_decode($result);
        if ($info['http_code'] != 201) {
        $message = 'Midtrans Error (' . $info['http_code'] . '): '
            . implode(',', $result_array->error_messages);
        throw new Exception($message, $info['http_code']);  //on this line
 
      }
```

**What I NEED:**

1. Redirect back to my `domain/orders` page and show some `Session::flash`
2. Get Order ID and transaction result (which is success) so I can save in my orders table in order to change status of my order in DB.

Thank you.

**Comment by harrypujianto** [comment]
https://snap-docs.midtrans.com/#snap-js
you can use onsuccess, onpending, onclose, and onerror. to show the result on the same page where the snap pop up open

**Comment by robertnicjoo** [comment]
@harrypujianto  and for retrieving data from midtrans?

**Comment by robertnicjoo** [comment]
@harrypujianto 
Ok i do get such info on my transaction:

![8574](https://user-images.githubusercontent.com/8672823/36718062-0cb4758c-1bd3-11e8-804e-a11a2dfe4d3f.jpg)

but still i'm redirecting to another page and receive error.

**Comment by eginugraha** [comment]
change 
`use App\Exceptions\VeritransException as VeritransException;`
to
`use App\Exceptions\VeritransException as Exception;`

**Comment by harrypujianto** [comment]
@eginugraha Thank you
