### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by justonjason** [harrypujianto/Veritrans-Laravel5#23]
Semua berjalan baik, tetapi saat saya mencoba checkout, popup payment snap tidak muncul, walau di console sudah loading dan muncul token snap-nya

**Comment by harrypujianto** [comment]
hmm.. tolong cek, di front end, apakah sudah mengguanakan snap js dengan url sesuai environment yang digunakan. (sanbox/production)

**Comment by justonjason** [comment]
oke siap akan saya cek kembali, mungkin ada yang miss saat development dengan tim saya.
terima kasih sarannya
