### ISSUE TITLE
snap issue

### ISSUE THREAD

**Issue by robertnicjoo** [harrypujianto/Veritrans-Laravel5#24]
Hi,

I get `status 200` on `SNAP` but there is no popup in my page, why is that?

![55](https://user-images.githubusercontent.com/8672823/40255747-799f0c2e-5b12-11e8-9ad1-801cd75d8e6a.png)

**Comment by robertnicjoo** [comment]
Anyone there?

**Comment by harrypujianto** [comment]
you've sucessfully open the snap didn't you? 
to troubleshoot this case, 
1. check the environment we're going to use. sandbox or production. did the key and endpoint match?
2. did we get the snap token?
3. if no, what is the error? if yes, did we successfully passed to the frontend? 
4. did we use the correct url to retrieve snap.js on the front end?

**Comment by robertnicjoo** [comment]
@harrypujianto OK, the problem was that I removed `echo $snap_token;` from controller, but I really need to know this:

**How do I save info from Midtrans to my database?**

What I need to save after user make his/her payment is : `timestamp` and `transaction status` i just need to save these to and update my orders table.

I have tried to add code below in my controller `try` part, and the result was not letting pop-up shows up,

```php
$snap_token = $midtrans->getSnapToken($transaction_data);
            echo $snap_token;
            

        // Success
        if($snap_token->transaction_status == 'capture') {
          echo "<p>Transaksi berhasil.</p>";
          echo "<p>Status transaksi untuk order id $snap_token->order_id: " .
              "$snap_token->transaction_status</p>";

          echo "<h3>Detail transaksi:</h3>";
          echo "<pre>";
          var_dump($snap_token);
          echo "</pre>";
        }
```

So what do you suggest me to do?

**Comment by harrypujianto** [comment]
hmm.. i dont think it's the correct purpose of the snap token. 

```
$snap_token = $midtrans->getSnapToken($transaction_data);
            echo $snap_token;
```
will return the token looks like a guid, we called snap token. 
the response you got from `getSnapToken` most likely looks like this
```
{
    "token": "d9aa448a-ffda-4310-ba66-e400131f8881",
    "redirect_url": "https://app.ssandbox.midtrans.com/snap/v2/vtweb/d9aa448a-ffda-4310-ba66-e400131f8881"
}
```
there is no transaction status and order id. 

we need to open the snap
[code open snap](https://github.com/harrypujianto/Veritrans-Laravel5/blob/master/resources/views/snap_checkout.blade.php#L45)

let your cust finish the txn. and you got the response
[result](https://github.com/harrypujianto/Veritrans-Laravel5/blob/master/resources/views/snap_checkout.blade.php#L47)

there's result onSuccess: function(`result`){

result contain the final response. you could send it to your backend, by using form post method, or any method you want. 
then you can parse the result. do not forget to decode. for example
```
$decoded_result=json.decode($result);
```
 on your controller. 

then you can do like you mention above

```
$orderid= $decoded_result->oder_id;
```

hmmm.. hope this clear..

**Comment by robertnicjoo** [comment]
Thanks for the response,
My point was to do something like you do have in vTrans sample codes where after try you provided getting results in controller so we can manage to what happen next such as updating database,

The points you've mentioned as JavaScript response won't help because as soon as transaction is done the page will reload to `echo $snap_token` and they'll disappear from the new page.

I also tried to use redirect method with snap_token in order to brings back results but unfortunately everything except echo will turn to error even red error in pop-up or avoiding of pop-up to open.

Q:

So base on what you say, that there is nothing we can do to get our results on controller, what way do you suggest me to send my JavaScript results back to the controller?

Because as it's online payment it has to take effect immediately after user attempted to pay where is success or not we have to give back something to our user so i really need to update my database row for that matter.


Break it down to you:

Simply tell me how to send JavaScript results to controller please?

Thank you.

**Comment by harrypujianto** [comment]
in the matter of updating your database in real time. we're sending http post notification for every state of transaction. we send the response directly to your backend. we should utilize this to update your database right away. 

[this function](https://github.com/harrypujianto/Veritrans-Laravel5/blob/master/app/Http/Controllers/VtwebController.php#L101)

this function using `veritrans` class, while get token snap using `midtrans`. please double check your code.

**Comment by robertnicjoo** [comment]
Exactly that's my point, it seems for `veritrans` you covered the backend but `Midtrans` brings whole a lot issues to get data in backend.

**I am using Midtrans** and not veritrans, that's why I'm facing this issue.

I want use `midtrans` but get the data that `veritrans` provides. I dont want to get token, i want to get transactions data (like the way veritrans provides)

**Comment by harrypujianto** [comment]
it is 2 diffrent library. 
the midtrans only cover the snap process. which is get token snap.
the other using veritrans. so i guess it's clear. sorry for the confusion

**Comment by robertnicjoo** [comment]
Thanks for the response,

I just needed to be clear that there is no way to pass snap results to controller by default and i am now, I'll make custom function for that matter and pass the data to my controller.

Thanks.
