### ISSUE TITLE
token issue

### ISSUE THREAD

**Issue by robertnicjoo** [harrypujianto/Veritrans-Laravel5#27]
Hi,

When I try to return results in specific route or page i'm getting error `400` but receiving token as well!

```php
try
{
            $snap_token = $midtrans->getSnapToken($transaction_data);
            $project->payment_verified = 'y';
            $project->save();

            //return redirect($vtweb_url);
            return redirect()->back()->with('success', 'Done '.$snap_token);
} 
catch (Exception $e) 
{   
            return $e->getMessage;
}
```

![400](https://user-images.githubusercontent.com/8672823/46657118-c0ee8900-cbd9-11e8-969f-8b322cbf2782.png)

but if i use default `echo $snap_token;` everything works just fine.

what is the issue with it?

**Comment by robertnicjoo** [comment]
anyone?

**Comment by harrypujianto** [comment]
can you make sure that the token passed to the front?
if you have, then this occured, means there's a trouble with the snap itself. Please contact support@midtrans.com
