### ISSUE TITLE
Exception Class Not Found

### ISSUE THREAD

**Issue by lexdorf** [harrypujianto/Veritrans-Laravel5#5]
Modify this line
use App\Exceptions\VeritransException as Exception;

error debug
PHP message: PHP Fatal error:  Class 'App\Veritrans\Exception' not found in

**Comment by harrypujianto** [comment]
modified

**Comment by JFOC** [comment]
The code is still using the old one

**Comment by robertnicjoo** [comment]
@harrypujianto  modified in where? still getting same error.
