### ISSUE TITLE
How to merge all the files?

### ISSUE THREAD

**Issue by krisnaw** [harrypujianto/Veritrans-Laravel5#8]
How to merge all the files?

**Comment by harrypujianto** [comment]
merge all file to your repo or this repo? if you want to merge to this repo, please create a pull request

**Comment by krisnaw** [comment]
I mean the second steps of installation. 
1. Download the library and extract the .zip
2. Merge all the files. (?)

**Comment by harrypujianto** [comment]
copy to your framework directory.
